- hosts: all
  tasks: 
  - name: install the latest packages
    yum:
      name: httpd
      state: latest
    register: hello  
    ignore_errors: yes

  - name: start apache
    service:
      name: httpd
      state: started      
    register: kaizen

  - debug: msg={{ hello }}  
  - debug: msg={{ kaizen }} 
